version: "3.8"
services:
  app:
    build: .
    container_name: streamflow-app
    restart: unless-stopped
    ports:
      - "7575:7575"
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamflow-app.rule=Host(`streamflow.hashira.studio`)"
      - "traefik.http.routers.streamflow-app.entrypoints=websecure"
      - "traefik.http.routers.streamflow-app.tls.certResolver=letsencrypt"
      - "traefik.http.services.streamflow-app.loadbalancer.server.port=7575"

networks:
  dokploy-network:
    external: true
